apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        # after checking the mogo docker image on dockerhub, it specified the below have to be given
        ports:
        - containerPort: 27017
        env:
        # as this file is going to be held on a public repo, we need a secret to store the values below in K8s
        # the name and key comes from the Secret config
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
# YAML syntax is triple dash for a new doc
# deployment and service usually go together so to prevent one getting lost, it's a good idea to have them in the same doc

apiVersion: v1
kind: Service
metadata:
  # this name can be anything
  name: mongodb-service
spec:
  selector:
    # attaches to the pod of the app with label of mongodb
    app: mongodb
  ports:
    - protocol: TCP
      # service port
      port: 27017
      # deployment port (of container which was referenced in the deployment - has to match)  
      targetPort: 27017
      # nb: these two ports can be different from eachother
