apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    env: {{ .Values.service.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    env: {{ .Values.service.env }}
