apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: dev
    region: us-east-1

nodeGroups:
    - name: standard-workers
      instanceType: t3.medium
      desiredCapacity: 3
      minSize: 1
      maxSize: 4